services:
  - type: web
    name: vibe-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: CORS_ORIGIN
        value: "*"
      - key: DB_DIALECT
        value: mysql
      - key: MYSQL_SSL
        value: "true"
      # Configure these in Render dashboard or here if safe
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        value: vibe
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES
        value: 7d


